/** Control-owned canonical record construction. */
import { initialDesignProposalRefFor, initialDesignDecisionRefFor, type InitialDesignProposalSnapshot, type InitialDesignDecisionSnapshot, type CoordinationPolicyRevisionSnapshot, type ProjectCoordinationPolicyActiveSnapshot, type RecordInitialDesignProposalCommand, type RecordInitialDesignDecisionCommand, type InstallCoordinationPolicyCommand, type ActivateCoordinationPolicyCommand, recordInitialDesignProposalFingerprint, recordInitialDesignDecisionFingerprint, installCoordinationPolicyFingerprint, activateCoordinationPolicyFingerprint } from "../../../contracts/human-role-collaboration.js";



// folds（compact —— 供双适配器 fold-equality）
export function buildP115ProposalFold(command: RecordInitialDesignProposalCommand, deps: { eventId: string; occurredAt: string }): import("../../../contracts/ledger.js").InitialDesignProposalRecordLedgerCommitV1 {
  const proposal = command.payload.proposal;
  const snap: InitialDesignProposalSnapshot = { ref: initialDesignProposalRefFor(proposal.projectId, proposal.workspaceId, proposal.designId), revision: 1, schemaVersion: 1, proposal, recordedAt: deps.occurredAt };
  return { commitKind: "initial-design-proposal-record", schemaVersion: 1, identity: { ...command.identity }, fingerprint: recordInitialDesignProposalFingerprint(command), expectedVersions: [{ ref: snap.ref, revision: 0 }], events: [{ eventId: deps.eventId, eventType: "InitialDesignProposalRecorded", schemaVersion: 1, projectId: proposal.projectId, workspaceId: proposal.workspaceId, aggregateType: "InitialDesignProposal", aggregateId: proposal.designId, aggregateRevision: 1, causationId: command.commandId, correlationId: command.correlationId, idempotencyKey: command.identity.idempotencyKey, actor: { ...command.identity.actor }, occurredAt: deps.occurredAt, payload: { proposal, recordedAt: deps.occurredAt } }], snapshots: [snap], outboxIntents: [] };
}

export function buildP115DecisionFold(command: RecordInitialDesignDecisionCommand, deps: { eventId: string; occurredAt: string }): import("../../../contracts/ledger.js").InitialDesignDecisionRecordLedgerCommitV1 {
  const decision = command.payload.decision;
  const snap: InitialDesignDecisionSnapshot = { ref: initialDesignDecisionRefFor(decision.projectId, decision.workspaceId, decision.decisionId), revision: 1, schemaVersion: 1, decision, recordedAt: deps.occurredAt };
  return { commitKind: "initial-design-decision-record", schemaVersion: 1, identity: { ...command.identity }, fingerprint: recordInitialDesignDecisionFingerprint(command), expectedVersions: [{ ref: snap.ref, revision: 0 }], events: [{ eventId: deps.eventId, eventType: "InitialDesignDecisionRecorded", schemaVersion: 1, projectId: decision.projectId, workspaceId: decision.workspaceId, aggregateType: "InitialDesignDecision", aggregateId: decision.decisionId, aggregateRevision: 1, causationId: command.commandId, correlationId: command.correlationId, idempotencyKey: command.identity.idempotencyKey, actor: { ...command.identity.actor }, occurredAt: deps.occurredAt, payload: { decision, recordedAt: deps.occurredAt } }], snapshots: [snap], outboxIntents: [] };
}

export function buildP115PolicyInstallFold(command: InstallCoordinationPolicyCommand, deps: { eventId: string; occurredAt: string }): import("../../../contracts/ledger.js").CoordinationPolicyInstallRecordLedgerCommitV1 {
  const snap: CoordinationPolicyRevisionSnapshot = { ref: { aggregateType: "CoordinationPolicyRevision", projectId: command.identity.projectId, policyId: command.payload.policyId, revision: 1 }, revision: 1, schemaVersion: 1, policyId: command.payload.policyId, contentRevision: 1, content: command.payload.content, contentDigest: command.payload.contentDigest, installedAt: deps.occurredAt };
  return { commitKind: "coordination-policy-install", schemaVersion: 1, identity: { ...command.identity }, fingerprint: installCoordinationPolicyFingerprint(command), expectedVersions: [{ ref: snap.ref, revision: 0 }], events: [{ eventId: deps.eventId, eventType: "CoordinationPolicyInstalled", schemaVersion: 1, projectId: command.identity.projectId, workspaceId: "", aggregateType: "CoordinationPolicyRevision", aggregateId: command.payload.policyId, aggregateRevision: 1, causationId: command.commandId, correlationId: command.correlationId, idempotencyKey: command.identity.idempotencyKey, actor: { ...command.identity.actor }, occurredAt: deps.occurredAt, payload: { revision: snap } }], snapshots: [snap], outboxIntents: [] };
}

export function buildP115PolicyActivateFold(command: ActivateCoordinationPolicyCommand, deps: { eventId: string; occurredAt: string; activeAggregateRevision: number; projectRevision: number }): import("../../../contracts/ledger.js").CoordinationPolicyActivateRecordLedgerCommitV1 {
  const snap: ProjectCoordinationPolicyActiveSnapshot = { ref: { aggregateType: "ProjectCoordinationPolicyActive", projectId: command.identity.projectId }, projectId: command.identity.projectId, activeRevision: command.payload.target.ref, revision: deps.activeAggregateRevision };
  return { commitKind: "coordination-policy-activate", schemaVersion: 1, identity: { ...command.identity }, fingerprint: activateCoordinationPolicyFingerprint(command), expectedVersions: [{ ref: { aggregateType: "Project" as const, projectId: command.identity.projectId }, revision: deps.projectRevision }, { ref: snap.ref, revision: deps.activeAggregateRevision - 1 }], events: [{ eventId: deps.eventId, eventType: "CoordinationPolicyActivated", schemaVersion: 1, projectId: command.identity.projectId, workspaceId: "", aggregateType: "ProjectCoordinationPolicyActive", aggregateId: command.identity.projectId, aggregateRevision: deps.activeAggregateRevision, causationId: command.commandId, correlationId: command.correlationId, idempotencyKey: command.identity.idempotencyKey, actor: { ...command.identity.actor }, occurredAt: deps.occurredAt, payload: { activeRef: snap.ref, activeRevision: snap.activeRevision } }], snapshots: [snap], outboxIntents: [] };
}