import fs from 'node:fs';import path from 'node:path';
import ts from '../../.local/linux-test-tools/node_modules/typescript/lib/typescript.js';
const root='evidence/2026-09-11-source-cleanup', baseline=JSON.parse(fs.readFileSync(root+'/baseline.json'));
const moves={...JSON.parse(fs.readFileSync(root+'/migrations.json')).moves,...JSON.parse(fs.readFileSync(root+'/host-support-migration.json')).moves};
const original=f=>fs.readFileSync(fs.existsSync(root+'/history/'+f+'.txt')?root+'/history/'+f+'.txt':f,'utf8');
const printer=ts.createPrinter({removeComments:true});
function declarations(file,source){const ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true);return ast.statements.filter(n=>!ts.isImportDeclaration(n)&&!ts.isExportDeclaration(n)).map(n=>{
 const transformed=ts.transform(n,[context=>{const visit=node=>{if(ts.isImportTypeNode(node)&&ts.isLiteralTypeNode(node.argument)&&ts.isStringLiteral(node.argument.literal)){const p=path.posix.normalize(path.posix.join(path.posix.dirname(file),node.argument.literal.text)).replace(/\.js$/,'.ts');return ts.factory.updateImportTypeNode(node,ts.factory.createLiteralTypeNode(ts.factory.createStringLiteral(moves[p]??p)),node.attributes,node.qualifier,node.typeArguments,node.isTypeOf);}return ts.visitEachChild(node,visit,context);};return visit;}]);
 const name=n.name?.getText(ast)??(ts.isVariableStatement(n)?n.declarationList.declarations.map(d=>d.name.getText(ast)).join(','):n.kind.toString());
 const text=printer.printNode(ts.EmitHint.Unspecified,transformed.transformed[0],ast);transformed.dispose();return {name,text};});}
const ignored=new Set(['VerificationControlPort','RecordedVerificationDeps','VerificationServiceDeps']);
const comparisons=[],differences=[];
for(const row of baseline.roots.product.files.filter(r=>r.path.startsWith('src/contracts/')&&r.path.endsWith('.ts')&&!/\/(fixtures|testing)\//.test(r.path)&&!r.path.endsWith('/index.ts'))){const f=row.path,dest=moves[f]??f;if(!fs.existsSync(dest)){differences.push({file:f,missing:dest});continue;}const before=declarations(f,original(f)).filter(d=>!ignored.has(d.name)),after=declarations(dest,fs.readFileSync(dest,'utf8'));const changed=before.filter(d=>!after.some(a=>a.name===d.name&&a.text===d.text));comparisons.push({file:f,destination:dest,declarations:before.length,unchanged:before.length-changed.length});for(const d of changed)differences.push({file:f,declaration:d.name});}
const report={checkedAt:new Date().toISOString(),scope:'Public contracts plus relocated ledger validation; compares all non-import/non-reexport declaration bodies with canonicalized inline type-import paths, excluding three module-private constructor dependency aliases.',comparisons,differences};fs.writeFileSync(root+'/compatibility.json',JSON.stringify(report,null,2));console.log(JSON.stringify({files:comparisons.length,declarations:comparisons.reduce((n,c)=>n+c.declarations,0),differences},null,2));if(differences.length)process.exitCode=1;
