import { createHash } from 'node:crypto';
import { copyFile, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { expect, it } from 'vitest';
import { SqliteStateLedger } from '../../src/data/state-ledger/sqlite-ledger.js';
import { createSqliteReadModelIndex } from '../../src/data/read-model-index/sqlite-read-model-index.js';
import { ControlPolicyExplanation } from '../../src/control/control-engine/policy-explanation.js';
import type { AggregateSnapshot, EventPage } from '../../src/contracts/ledger.js';
import type { CommitCursor } from '../../src/contracts/command-event.js';

// This file is a preserved RAT-03 database, not a database generated by today's writer.
const historical = resolve('evidence/rat-03/platform-dispatch/recovery-exactly-once-trial-1/gui-data/projects/local-0e240f792710932932cd/ledger.sqlite');
it('opens a preserved RAT-03 ledger, retains its exact canonical facts and rebuilds current projections', async () => {
  const bytes = await readFile(historical), digest = createHash('sha256').update(bytes).digest('hex');
  const dir = await mkdtemp(join(tmpdir(), 'historical-ledger-'));
  const path = join(dir, 'ledger.sqlite'); await copyFile(historical, path);
  const original = new DatabaseSync(path, { readOnly: true });
  const snapshots = original.prepare('SELECT snapshot_json FROM snapshots ORDER BY ref_key').all().map(row => JSON.parse(String(row['snapshot_json'])) as AggregateSnapshot);
  const eventCount = Number(original.prepare('SELECT COUNT(*) AS n FROM events').get()!['n']);
  original.close();
  let ledger = new SqliteStateLedger({ path });
  const projection = createSqliteReadModelIndex({ path: join(dir, 'rebuilt.sqlite'), policyExplanation: new ControlPolicyExplanation() });
  try {
    expect(snapshots.length).toBeGreaterThan(0); expect(eventCount).toBeGreaterThan(0);
    for (const snapshot of snapshots) expect(await ledger.load(snapshot.ref)).toMatchObject({ status: 'found', snapshot });
    let cursor: CommitCursor | null = null, applied = 0;
    for (;;) {
      const page: EventPage = await ledger.events({ afterCursor: cursor, limit: 100 });
      const receipt = await projection.advance(page);
      expect(receipt.throughCursor).toBe(page.throughCursor);
      applied += receipt.appliedEventIds.length;
      cursor = page.throughCursor;
      if (!page.hasMore) break;
    }
    expect(applied).toBe(eventCount);
    await ledger.close(); ledger = new SqliteStateLedger({ path });
    for (const snapshot of snapshots) expect(await ledger.load(snapshot.ref)).toMatchObject({ status: 'found', snapshot });
    expect(createHash('sha256').update(await readFile(historical)).digest('hex')).toBe(digest);
  } finally { await projection.close(); await ledger.close(); await rm(dir, { recursive: true, force: true }); }
});
