import fs from 'node:fs';import path from 'node:path';
const product=process.cwd(),root=path.resolve('../agent_learn/agent_dev/agent_platform'),dir='evidence/2026-09-11-architecture-convergence';
const browser=fs.readFileSync(dir+'/browser-accepted-2.log','utf8');if(!/25 passed/.test(browser))throw Error('Browser final has not passed');
let p=path.join(root,'dev_docs/verification/2026-09-11-architecture-convergence/summary.md'),s=fs.readFileSync(p,'utf8');const a=s.indexOf('## 验证记录'),b=s.indexOf('## 收口后停止',a);
const link=(f)=>path.relative(path.dirname(p),path.join(product,dir,f)).replaceAll('\\','/');
s=s.slice(0,a)+`## 最终验证与结论\n\n确认偏差已修复，12 Module均有结论，用户所需C类选择已明确且按决定实施；本次没有遗留待决架构项。未参与实现者已复核责任、可读性与有效义务承接，发现的错误已闭合。\n\n| 检查 | 实际结果 |\n| --- | --- |\n| 最终全仓行为回归 | 296文件、1939项全部PASS；[日志](${link('full-tests-final.log')}) |\n| 浏览器真实服务/工作台 | 25项全部PASS，使用现有Chromium与bwrap；[日志](${link('browser-accepted-2.log')}) |\n| 类型/构建/模块结构 | 后端及测试类型、前端严格类型、产品构建exit0；410文件归属/409解析，0边界问题；340非UI编译JS无旧路径孤儿 |\n| 文档 | 13/13检查PASS；最终文档复核另见[报告](${link('final-review-docs.md')}) |\n| 独立反例 | 4项正式Evidence/unknown反例PASS，已纳入全仓；数据11项与规划39项专项PASS |\n\n[完整命令与日志索引](${link('verification.md')})保留首轮全仓2项失败、原测试夹具/类型错误、Windows依赖调用失败、两轮浏览器环境失败和一次端口占用。没有覆盖失败日志；独立审查所发现的治理矩阵混版、未知误报及5项文案错误均已闭合。真实模型质量、公开基准和完整自治闭环未因本次框架/浏览器验收而宣称完成。\n\n[最终源码与文档身份](${link('final.json')})包括两个HEAD、未提交文件逐项SHA256与总体摘要；[变化清单](${link('convergence-changes.json')})对照恢复身份。构建产物与测试结果另留证据，不当产品源码。全仓候选后仅清除了7个多余type导入，导出及运行行为不变，前端严格类型和最终浏览器构建已复验。\n\n`+s.slice(b);fs.writeFileSync(p,s);
p='IMPLEMENTATION-HANDOFF.md';s=fs.readFileSync(p,'utf8').replace('最终回归与浏览器验收进行中','全仓296文件/1939项、浏览器25项、前后端类型、构建、结构与文档验证通过').replace('完成验收后停止，不启动新功能。','本次验收已完成并停止，不启动新功能。');fs.writeFileSync(p,s);
p=path.join(root,'human/module-status.md');s=fs.readFileSync(p,'utf8');s=s.replace('最终汇总由主Agent在完成实际运行后补充。本页不把正在进行的全回归写成完成。','最终实测：296文件/1939项行为测试、25项浏览器测试全部通过；前后端类型与构建通过、模块结构0问题、文档13/13。完整命令、身份与历史失败见[本次偏差摘要](../dev_docs/verification/2026-09-11-architecture-convergence/summary.md)。本次架构收口完成并停止，不启动下一阶段功能。');fs.writeFileSync(p,s);
p=dir+'/verification.md';s=fs.readFileSync(p,'utf8').replace('正在运行，[browser-accepted-2.log](browser-accepted-2.log)；完成后更新','25项全部PASS，[browser-accepted-2.log](browser-accepted-2.log)，最终浏览器构建使用清除多余类型导入后的源码').replace('5个小文案/路径错误已反馈主Agent修正，最终追加核对为准。','5个小文案/路径错误已修正，独立审阅者已追加结案确认。');fs.writeFileSync(p,s);
