import { chromium } from '/mnt/c/Users/han001/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import { createGuiServer } from '../../dist/app/server.js';
import { prepareRuntimeWorkspace } from '../../dist/runtime/coding-agent-runtime.js';
import { resolve, join, relative } from 'node:path';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';
if (process.env.RAT02_LIVE !== '1') throw Error('Explicit RAT02_LIVE=1 required for a paid trial');
const root = '/tmp/rat02-live-slug-20260907';
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
async function files(dir = root) { const result = {}; for (const entry of await readdir(dir, { withFileTypes: true })) { const p = join(dir, entry.name); if (entry.isDirectory()) Object.assign(result, await files(p)); else if (entry.isFile()) result[relative(root, p)] = hash(await readFile(p)); else throw Error('unexpected symlink'); } return result; }
const report = { stage: 'RAT-02', task: 'python-slug-normalization', trial: 1, browserChecks: [], model: 'deepseek-v4-flash-vision-exp' };
let app, browser;
try {
  report.nodeSha256 = await prepareRuntimeWorkspace(root);
  report.before = await files();
  report.startedAt = new Date().toISOString();
  const instruction = await readFile(join(root, 'TASK.md'), 'utf8');
  app = await createGuiServer(resolve('.local/gui'));
  await new Promise(r => app.server.listen(0, '127.0.0.1', r));
  const base = `http://127.0.0.1:${app.server.address().port}`;
  browser = await chromium.launch({ executablePath: '/home/han001/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome', headless: true, args: ['--no-sandbox'], env: { ...process.env, FONTCONFIG_FILE: resolve('.local/rat-01-fonts/fonts.conf') } });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(base);
  await page.locator('#model-settings-open').click(); await page.waitForFunction(() => document.querySelector('#model-name').value !== '');
  assert.equal(await page.locator('#model-name').inputValue(), report.model);
  await page.locator('[data-close="model-settings-dialog"]').click();
  await page.locator('#add-project').click(); await page.locator('#project-folder-path').fill(root);
  await page.getByRole('button', { name: '添加并打开', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('#project-dialog').open);
  await page.locator('#new-goal').click(); await page.locator('#new-objective').fill(instruction);
  await page.getByRole('button', { name: '创建目标', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('#goal-dialog').open);
  await page.locator('#project-tab').click(); await page.locator('#real-task-open').click();
  await page.locator('#real-task-write').check();
  await page.locator('#real-task-form summary').click();
  await page.locator('#real-request-limit').fill('10'); await page.locator('#real-tool-limit').fill('30'); await page.locator('#real-time-limit').fill('30');
  const accepted = page.waitForResponse(r => r.url().endsWith('/api/real/tasks'));
  await page.locator('#real-task-submit').click(); const response = await accepted;
  const acceptedBody = await response.json(); report.accepted = { status: response.status(), body: acceptedBody }; assert.equal(response.status(), 200);
  await page.waitForFunction(() => !document.querySelector('#real-task-dialog').open);
  await page.locator('#chat-tab').click();
  await page.reload(); report.browserChecks.push('refresh-after-submit');
  await page.waitForFunction(() => { const r = document.querySelector('[data-real-status]'); return r && !['running', 'prepared'].includes(r.dataset.realStatus); }, { timeout: 45000 });
  const url = new URL(page.url());
  const query = new URLSearchParams({ projectId: url.searchParams.get('projectId'), workspaceId: url.searchParams.get('workspaceId'), goalId: url.searchParams.get('goalId') });
  const state = await (await fetch(base + '/api/state?' + query)).json();
  report.run = state.liveRuns.find(r => r.spec.runId === acceptedBody.runId);
  report.platformAgents = state.agents; report.platformMatrix = state.matrix; report.platformTimeline = state.timeline;
  await page.screenshot({ path: 'evidence/rat-02/gui-live-result.png', fullPage: true });
  report.browserErrors = errors; report.browserChecks.push('real-run-and-session-visible', 'real-mode-label');
  await app.close(); app = undefined;
  report.after = await files();
  report.changedPaths = [...new Set([...Object.keys(report.before), ...Object.keys(report.after)])].filter(p => report.before[p] !== report.after[p]);
  const evaluator = resolve('vendor/coding-agent/benchmarks/tasks/python-slug-normalization/hidden_tests/evaluate.py');
  const score = spawnSync('python3', [evaluator, root], { encoding: 'utf8', timeout: 10000, env: { ...process.env, PYTHONDONTWRITEBYTECODE: '1' } });
  report.evaluation = { exitCode: score.status, stdout: score.stdout, stderr: score.stderr };
  report.status = report.run.status === 'completed' && score.status === 0 && report.changedPaths.every(p => p === 'slug.py') && errors.length === 0 ? 'PASS' : 'FAIL';
  report.finishedAt = new Date().toISOString();
  await writeFile('evidence/rat-02/browser-live.json', JSON.stringify(report, null, 2) + '\n');
  console.log(JSON.stringify({ status: report.status, changedPaths: report.changedPaths, evaluation: report.evaluation, usage: report.run.usage, runStatus: report.run.status, browserErrors: errors }, null, 2));
} catch (error) { report.status = 'FAIL'; report.error = String(error).replace(/sk-[A-Za-z0-9_-]+/g, '[redacted]'); await writeFile('evidence/rat-02/browser-live.json', JSON.stringify(report, null, 2) + '\n'); console.log(JSON.stringify({ status: report.status, error: report.error, accepted: report.accepted })); process.exitCode = 1; }
finally { await browser?.close(); await app?.close(); }
