import {edit,replace} from './edit.mjs';
edit('src/contracts/planning.ts',s=>{
 const a=s.indexOf('/** Existing amendment requests'),b=s.indexOf('export type PlanProposalResult',a);
 const comment=s.slice(a,b);s=s.slice(0,a)+s.slice(b);
 return replace(s,'export interface PlanCompilerPort {',comment+"export interface PlanCompilerPort {\n  /** Bounded amendment proposal; no Control write. */").replace('  requestInitial(intent:', '  /** Persist a read-only initial-coordination request through Control. */\n  requestInitial(intent:');
});
edit('src/contracts/goal-change.ts',s=>s.replace(/\/\/ -+ \/\/\r?\n\/\/ Planning context[^\n]+\r?\n\/\/ -+ \/\/\r?\n\r?\n/,''));
edit('src/contracts/work-context-port.ts',s=>s.replace('P1-16 ContextCompiler.WorkContextPort — bounded work-context assembly','ContextCompiler.WorkContextPort — bounded work-context assembly').replace(' * (first consumer freeze of ContextCompiler.WorkContextPort).\r\n','').replace('bounded assembly (interfaces_to_freeze)','bounded assembly'));
for(const file of ['tests/contract-suite/p1-09-harness.ts','tests/contract-suite/p1-16-harness.ts','tests/contract-suite/p1-17-harness.ts'])edit(file,s=>s.replace('world + helpers (FROZEN surface; lanes fill submit/answer/close/drive/view).','world + helpers. Both adapters consume the same Control and Context interfaces.').replace(/ \* The helper surface below is FROZEN[\s\S]*?helpers only call frozen signatures\./,' * Control owns work records; Context owns projection and bounded material assembly.').replace(/ \* path\. The helper surface is FROZEN[\s\S]*?completedWorkView \+ assembleCompletedWorkContext\./,' * path. Selection uses the existing completedWork module object.'));
edit('src/control/plan-compiler/README.md',s=>s.replace('统一 request／accept 入口','request（变更提案）、requestInitial（初始协调）／accept（消费协调结果）入口'));
edit('src/data/context-compiler/README.md',s=>replace(s,'编译器入口存在不表示角色消费已经接通；实际执行输入从 runtime-context 追踪到 runtime。','编译器入口存在不表示角色消费已经接通；实际执行输入从 runtime-context 追踪到 runtime。规划材料的请求、结果、拒绝码与端口统一定义于 `contracts/planning.ts`，实现与测试直接消费该协议，不再重复声明字段。'));
edit('src/harness/README.md',s=>replace(s,'默认夹具注入不等于真实能力；','规划/补料消费者直接使用已有 `planProposal.request`、`planningContext.assemblePlanningContext`、`queryContext.assembleQueryContext`、`workContext.assembleWorkContext`、`completedWork.assembleCompletedWorkContext`；计划正式受理走 `control.recordPlanChangeProposal/recordUserDecision/applyPlanChange`，人的变更入口为 `collaboration.amend`。两宿主不再为这些方法另建同名转发面。带投影推进的授权入口与带问题材料预取的返工组合入口仍保留，不能按纯转发删除。\n\n默认夹具注入不等于真实能力；'));
edit('src/contracts/README.md',s=>s+`\n规划协议由 [planning.ts](planning.ts) 统一定义请求与结果；PlanProposalPort 已移除，窄消费者使用 PlanCompilerPort 的 request。初始协调改用 requestInitial，持久 QueryJob 与 HTTP 形状不变。返工草稿直接派生自 PlanRevisionDraft 并要求完整任务/指派；普通变更仍保留 null/省略的历史语义，不把二者强制等同。\n`);
const docs='../agent_learn/agent_dev/agent_platform/';
edit(docs+'dev_docs/modules/control/plan-compiler.md',s=>s.replace(/候选操作：[^\r\n]+/,'当前操作：`request(amendment)` 形成变更提案，`requestInitial(intent)` 请求初始只读协调，`accept(trigger)` 消费已持久化结果。共享协议以 `contracts/planning.ts` 为源码权威；完整语义协调能力仍按当前模块状态验收，不由这些入口存在推定。').replace('暴露统一 request/accept','暴露 request/requestInitial/accept').replace('`control/policies/initial-plan-admission.ts`','`control/control-engine/policies/initial-plan-admission.ts`'));
edit(docs+'dev_docs/modules/data/context-compiler.md',s=>s+'\n规划材料的 `PlanningContextPort`、请求、结果与拒绝码统一在 `contracts/planning.ts` 定义，Context 的 `planning-context-compiler.ts` 直接实现；harness 与契约测试直接消费既有编译器对象。仍保留委托 TaskContext 的范围检查、预算、缺口及拒绝映射，未把编译器本身删除或转给组合根。\n');
edit(docs+'dev_docs/interfaces/module-boundaries.md',s=>s.replace('`planning.ts` 的 request/accept','`planning.ts` 的 request/requestInitial/accept').replace('PlanCompiler request 通过 Control 保存 QueryJob','PlanCompiler requestInitial 通过 Control 保存 QueryJob')+'\n计划变更提案与规划 Context 的公开形状统一位于 `contracts/planning.ts`；旧 PlanProposalPort 不再维护第二份接口。PlanRevisionDraft 是计划字段权威，返工必须给出完整任务和指派，普通变更保留旧的省略/null语义。两种宿主的九类纯转发入口已迁移到既有模块对象（规划、Context、Control和HumanCollaboration），授权投影推进及Verification材料预取仍由组合根完成。此收敛改变源码导入/调用路径，不改变持久字段、HTTP或模块依赖方向。\n');
edit(docs+'dev_docs/interfaces/runtime-collaboration.md',s=>s.replace(/\| PlanCompiler \|[^\r\n]+/,'| PlanCompiler | 当前 `request(amendment)` → proposal / needs_material / rejected；`requestInitial(intent)` → accepted(submission) / rejected；`accept(trigger)` → processed / rejected | ContextCompiler 提供材料；通过 ControlEngine 持久化初始协调请求并受理结果。完整咨询、冲突协商和 FAIL 语义调整仍需各自真实消费者；源码协议见 contracts/planning.ts |'));
